default_language_version:
  python: python3.9
default_stages:
  - commit
fail_fast: true
repos:
  - repo: https://github.com/psf/black
    rev: 21.11b1
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args:
          - "--ignore=E203,E501,W503"
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.5.0
    hooks:
      - id: eslint
        types:
          - file
        files: \.(js|vue)$
        args:
          - "--config"
          - "web/.eslintrc.js"
          - "--ext"
          - ".js,.vue"
          - "--ignore-path"
          - "web/.gitignore"
        additional_dependencies:
          - "eslint@8.5.0"
          - "eslint-plugin-vue@8.2.0"
          - "eslint-config-prettier@8.3.0"
          - "eslint-plugin-cypress@2.12.1"
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        args:
          - "--ignore-path"
          - "web/.prettierignore"
