[build.environment]
  NODE_VERSION = "16"
  NPM_FLAGS = "--version" # prevent Netlify npm install

[build]
  base = "web/"
  command = "npx pnpm install --store=node_modules/.pnpm-store && npx pnpm build"
  publish = "dist/"
  ignore = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_BASE_URL = "https://awesomepowertexasapi.com"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
    default-src 'none';
    connect-src https://awesomepowertexasapi.com https://*.awesomepowertexasapi.com https://*.herokuapp.com https://www.google-analytics.com;
    script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://www.google-analytics.com;
    style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
    font-src https://fonts.gstatic.com;
    img-src 'self' data: https://www.google-analytics.com;
    manifest-src 'self';
    frame-ancestors 'none'"""

    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[plugins]]
  package = "/netlify/plugins/api-base-url-env"
