[tool.poetry]
name = "awesomepower"
version = "1.0.0"
description = ""
authors = ["Michael Hays <michaelhays36@gmail.com>"]
license = "GPL-3.0"

[tool.poetry.dependencies]
python = "3.9.1"
Django = "^3.1.7"
django-cors-headers = "^3.7.0"
djangorestframework = "^3.12.4"
dj-database-url = "^0.5.0"
factory-boy = "^3.2.0"
google-cloud-vision = "^2.2.0"
gunicorn = "^20.1.0"
html2text = "^2020.1.16"
pandas = "^1.2.3"
pdf2image = "^1.14.0"
psycopg2-binary = "^2.8.6"
requests = "^2.25.1"
scipy = "^1.6.2"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
ptpython = "^3.0.17"
pylint = "^2.7.4"
pytest = "^6.2.2"
pytest-cov = "^2.11.1"
pytest-django = "^4.1.0"
pytest-dotenv = "^0.5.2"
python-dotenv = "^0.16.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
