# Generated by Django 3.1.1 on 2020-09-18 00:00

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.TextField()),
                ("ptc_name", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("rating", models.IntegerField(default=-1)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Tdu",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.TextField()),
                ("ptc_name", models.TextField()),
                (
                    "charges",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.DecimalField(decimal_places=2, max_digits=4),
                        size=None,
                    ),
                ),
                (
                    "rates",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.DecimalField(decimal_places=6, max_digits=6),
                        size=None,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "efl_numbers",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.DecimalField(decimal_places=6, max_digits=10),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "charge_function",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.DecimalField(
                                decimal_places=2, max_digits=6
                            ),
                            size=2,
                        ),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "rate_function",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.DecimalField(
                                decimal_places=6, max_digits=10
                            ),
                            size=2,
                        ),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "successful_function_name",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                (
                    "low_usage_rate",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=4, null=True
                    ),
                ),
                (
                    "medium_usage_rate",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=4, null=True
                    ),
                ),
                (
                    "high_usage_rate",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=4, null=True
                    ),
                ),
                ("ptc_idkey", models.IntegerField()),
                ("kwh_500", models.DecimalField(decimal_places=3, max_digits=3)),
                ("kwh_1000", models.DecimalField(decimal_places=3, max_digits=3)),
                ("kwh_2000", models.DecimalField(decimal_places=3, max_digits=3)),
                (
                    "rate_type",
                    models.IntegerField(
                        choices=[(0, "Variable"), (1, "Fixed"), (2, "Indexed")]
                    ),
                ),
                ("is_prepaid", models.BooleanField()),
                ("is_time_of_use", models.BooleanField()),
                ("is_promotion", models.BooleanField()),
                ("is_new_customer", models.BooleanField()),
                ("percent_renewable", models.IntegerField()),
                ("term", models.IntegerField()),
                ("cancellation_fee", models.TextField()),
                (
                    "language",
                    models.IntegerField(choices=[(0, "English"), (1, "Spanish")]),
                ),
                ("terms_url", models.URLField(max_length=500)),
                ("facts_url", models.URLField(max_length=500)),
                ("enroll_url", models.URLField(max_length=500)),
                ("enroll_phone", models.TextField()),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="plans.provider"
                    ),
                ),
                (
                    "tdu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="plans.tdu"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
