name: test
on:
  - push
jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgres://awesomepower:awesomepower@localhost:5432/awesomepower
      DJANGO_DEBUG: "TRUE"
      DJANGO_SECRET_KEY: dev
    services:
      postgres:
        image: postgres:12.4
        env:
          POSTGRES_DB: awesomepower
          POSTGRES_PASSWORD: awesomepower
          POSTGRES_USER: awesomepower
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9.1
      - name: Run image
        uses: abatilo/actions-poetry@v2.1.0
      - name: Install Python dependencies
        working-directory: backend
        run: poetry install
      - name: Migrate database
        working-directory: backend
        run: poetry run python manage.py migrate
      - name: Run Django server
        working-directory: backend
        run: poetry run gunicorn awesomepower.wsgi:application --daemon
      - name: Run pytest
        working-directory: backend
        run: poetry run pytest --cov-report=xml
      - uses: actions/setup-node@v2
        with:
          node-version: 14.9.0
      - name: Install Cypress dependencies
        run: sudo apt-get install libgbm-dev libnotify-dev
      - name: Run Cypress
        uses: cypress-io/github-action@v2.9.7
        with:
          working-directory: web
          start: yarn dev
          wait-on: http://localhost:3000
          record: true
        env:
          API_BASE_URL: http://localhost:8000
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload backend to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./backend/coverage.xml
          fail_ci_if_error: true
      - name: Upload web to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./web/coverage/coverage-final.json
          fail_ci_if_error: true
