// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./src/components/_global/AppButton.vue')['default']
    LoadingSpinner: typeof import('./src/components/_global/LoadingSpinner.vue')['default']
    TransitionExpand: typeof import('./src/components/_global/TransitionExpand.vue')['default']
  }
}

export { }
