// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./src/components/_global/AppButton.vue')['default']
    FontAwesomeIcon: typeof import('./src/components/_global/FontAwesomeIcon.vue')['default']
    LoadingSpinner: typeof import('./src/components/_global/LoadingSpinner.vue')['default']
    TransitionExpand: typeof import('./src/components/_global/TransitionExpand.vue')['default']
  }
}

export { }
